export class Config {
  static view_size = 15
  static maze_size = 50 
  static fork_min = 2
  static fork_max = 2
  static hazard_check_ms = 50
  static hazard_trigger_chance = 0.004
  static event_warning_duration_ms = 10000
  static event_warning_clear_duration_ms = 300
  static max_keys_held = 3
  static safety_tile_min = 3
  static safety_tile_max = 6
  static coin_min = 6
  static coin_max = 14
  static teleporter_unlock_cost = 8
  static drill_unlock_cost = 10
  static drill_use_cost = 3
  static recall_unlock_cost = 12
  static recall_use_cost = 4
}